import { build } from "esbuild";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";

const root = process.cwd();
const sourceDir = path.join(root, "mcp-app", "src");
const outputDir = path.join(root, "server", "generated");
const [bundle] = (await build({
  entryPoints: [path.join(sourceDir, "theme-studio.js")],
  bundle: true,
  format: "esm",
  minify: true,
  target: "es2022",
  write: false,
})).outputFiles;
const [template, css] = await Promise.all([
  readFile(path.join(sourceDir, "theme-preview.template.html"), "utf8"),
  readFile(path.join(sourceDir, "theme-studio.css"), "utf8"),
]);
const html = template
  .replace("__DEXTHEMES_WIDGET_CSS__", () => css)
  .replace("__DEXTHEMES_WIDGET_JS__", () => bundle.text);
if (!html.includes(bundle.text)) {
  throw new Error("Generated MCP widget did not preserve the bundled JavaScript exactly");
}
await mkdir(outputDir, { recursive: true });
await writeFile(
  path.join(outputDir, "theme-preview-html.js"),
  `// Generated by scripts/build-mcp-app.mjs\nexport const THEME_PREVIEW_HTML = ${JSON.stringify(html)};\n`,
);
